"""
settings.py — All tunable iRacing graphics settings with metadata.
Drives the optimizer and UI. Ordered by impact_weight descending.
"""

from typing import Optional

SETTINGS: list[dict] = [
    {
        "key": "AntiAliasMethod",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "enum",
        "values": [0, 1, 2, 3],
        "min": None,
        "max": None,
        "impact_weight": 10,
        "display_name": "Anti-Aliasing Method",
        "description": "AA technique: 0=None, 1=MSAA, 2=FXAA, 3=SMAA",
        "depends_on": None,
    },
    {
        "key": "MSAASamples",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "enum",
        "values": [2, 4, 8],
        "min": None,
        "max": None,
        "impact_weight": 9,
        "display_name": "MSAA Sample Count",
        "description": "Number of MSAA samples — only applies when AntiAliasMethod=1",
        "depends_on": {"AntiAliasMethod": 1},
    },
    {
        "key": "DynamicShadowRes",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 4,
        "impact_weight": 8,
        "display_name": "Dynamic Shadow Resolution",
        "description": "Shadow map resolution (per map, x3 total): 0=512, 1=1024, 2=2048, 3=4096, 4=8192",
        "depends_on": None,
    },
    {
        "key": "ShaderQuality",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 3,
        "impact_weight": 7,
        "display_name": "Shader Quality",
        "description": "0=Low, 1=Med, 2=High, 3=Max",
        "depends_on": None,
    },
    {
        "key": "FoliageDetail",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 3,
        "impact_weight": 6,
        "display_name": "Foliage Detail",
        "description": "Level of foliage/vegetation detail: 0=Off, 1=Low, 2=Med, 3=High",
        "depends_on": None,
    },
    {
        "key": "CrowdDetail",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 3,
        "impact_weight": 5,
        "display_name": "Crowd Detail",
        "description": "Spectator crowd rendering quality: 0=Off to 3=High",
        "depends_on": None,
    },
    {
        "key": "WeekendDetail",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 2,
        "impact_weight": 5,
        "display_name": "Weekend Detail",
        "description": "Pit/paddock scenery detail level: 0=Low, 1=Med, 2=High",
        "depends_on": None,
    },
    {
        "key": "CarDetail",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 2,
        "impact_weight": 4,
        "display_name": "Car Detail",
        "description": "Opponent car model detail: 0=Low, 1=Med, 2=High",
        "depends_on": None,
    },
    {
        "key": "LODPctMax",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "enum",
        "values": [100, 150, 200, 300, 400],
        "min": None,
        "max": None,
        "impact_weight": 4,
        "display_name": "LOD Distance Max (%)",
        "description": "Maximum level-of-detail draw distance as a percentage: 100–400",
        "depends_on": None,
    },
    {
        "key": "SSRLevel",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 2,
        "impact_weight": 3,
        "display_name": "Screen Space Reflections",
        "description": "SSR quality level: 0=Off, 1=Low, 2=High",
        "depends_on": None,
    },
    {
        "key": "ParticleDetail",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 2,
        "impact_weight": 3,
        "display_name": "Particle Detail",
        "description": "Tire smoke, dirt, and spark particle density: 0=Low, 1=Med, 2=High",
        "depends_on": None,
    },
    {
        "key": "GrandstandDetail",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 2,
        "impact_weight": 2,
        "display_name": "Grandstand Detail",
        "description": "Grandstand structure rendering detail: 0=Low, 1=Med, 2=High",
        "depends_on": None,
    },
    {
        "key": "HeadlightLevel",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "int",
        "values": None,
        "min": 0,
        "max": 2,
        "impact_weight": 2,
        "display_name": "Headlight Quality",
        "description": "Dynamic headlight rendering quality: 0=Off, 1=Low, 2=High",
        "depends_on": None,
    },
    {
        "key": "ShadowDetail",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "bool",
        "values": [0, 1],
        "min": None,
        "max": None,
        "impact_weight": 2,
        "display_name": "Shadow Detail",
        "description": "Enable high-quality shadow details: 0=Off, 1=On",
        "depends_on": None,
    },
    {
        "key": "MirrorDetail",
        "section": "Graphics Options",
        "file": "rendererDX11.ini",
        "type": "bool",
        "values": [0, 1],
        "min": None,
        "max": None,
        "impact_weight": 1,
        "display_name": "Mirror Detail",
        "description": "High-detail rear-view mirrors: 0=Low, 1=High",
        "depends_on": None,
    },
]

SETTINGS_BY_KEY: dict[str, dict] = {s["key"]: s for s in SETTINGS}
